name: Déploiement Modèle
run-name: Déploiement de ${{ github.ref_name }} par ${{ github.actor }}

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t modele_assuraimant:latest .

      - name: Run tests with pytest inside Docker
        run: |
          docker run --rm modele_assuraimant:latest pytest