name: Python CI


on:
  push:
    branches: [ main, develop, gauthier ] # Uniquement sur push vers main ou develop
  pull_request:
    branches: [ main ]       # Uniquement sur PR ciblant main

jobs:
  test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: Install depedencies
          run: | # Permet d'exécuter plusieurs commandes
            python -m pip install --upgrade pip
            pip install pytest pytest-cov
            # Si vous avez un fichier requirements.txt:
            pip install -r requirements.txt

        - name: Run lint with flake8
          run: flake8  

        - name: Run tests with pytest
          run: pytest --cov=src --cov-report=term-missing

  call-deployment:
    name: Deploy on docker (after part 3)
    uses: ./.github/workflows/cd.yml
    needs: test
