name: Python CI

on: [push, pull_request] # Déclenché sur un push ou une pull request

# Ou plus spécifiquement :
on:
  push:
    branches: [ main, develop, gauthier ] # Uniquement sur push vers main ou develop
  pull_request:
    branches: [ main ]       # Uniquement sur PR ciblant main

jobs:
  test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup_python@v5
          with:
            python-version: '3.10'

        - name: Install depedencies
          run: | # Permet d'exécuter plusieurs commandes
            python -m pip install --upgrade pip
            pip install pytest
            # Si vous avez un fichier requirements.txt:
            # pip install -r requirements.txt

        - name: Run tests with pytest
          run: pytest 

